import React from 'react'
import Carousel_flowbite from '../Components/Carousel_flowbite';

export const metadata = {
    title: "Carousel_flowbite",
    description: "Generated by create next app",
  };

export default function page() {
    return (
        <>
            <div>

                <Carousel_flowbite />
            </div>
         

        </>
    );
}
