import React from 'react'
import CardFlowbite from '../Components/Card - Flowbite'

export const metadata = {
    title: "card flowbite",
    description: "Generated by create next app",
  };
export default function React_card_flowbite() {
    return (
        <div><CardFlowbite /></div>
    )
}
