import React from 'react'
import React_Tabs from '../Components/React_Tabs';

export const metadata = {
    title: "Tabs",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <div>

        <React_Tabs/>
    </div>
  )
}
