import React from 'react'
import Forms_flowbites from '../Components/Forms_flowbites'
export const metadata = {
  title: "form flowbite",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div><Forms_flowbites/></div>
  )
}
