import React from 'react'
import { Progress } from "flowbite-react";

export const metadata = {
    title: "ratReact Progress Bar - Flowbiteing",
    description: "Generated by create next app",
};
export default function App_Progress() {
    return (
        <>

            <h1 className='mb-2 inline-block w-full text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white text-center'>React Progress Bar - Flowbite</h1>

            <div>
                <Default_progress_bar />
                <Progress_bar_with_labels />
                <Label_positioning />
                <Sizing />
                <Colors />
            </div>
        </>
    )
}
function Default_progress_bar() {

    return (

        <>
            <div>
                <h2 className='text-center text-red-600 font-medium'>Default_progress_bar</h2>


                <Progress progress={45} />
            </div>

        </>
    )
}
function Progress_bar_with_labels() {

    return (

        <>
            <div>
                <h2 className='text-center text-red-600 font-medium'>Progress_bar_with_labels</h2>


                <Progress progress={50} textLabel="Flowbite" size="lg" labelProgress labelText />
            </div>

        </>
    )
}
function Label_positioning() {

    return (

        <>
            <div>
                <h2 className='text-center text-red-600 font-medium'>Label_positioning</h2>


                <Progress
                    progress={45}
                    progressLabelPosition="inside"
                    textLabel="Flowbite"
                    textLabelPosition="outside"
                    size="lg"
                    labelProgress
                    labelText
                />
            </div>

        </>
    )
}
function Sizing() {

    return (

        <>
            <div>
                <h2 className='text-center text-red-600 font-medium'>Sizing</h2>


                <div className="flex flex-col gap-2">
                    <div className="text-base font-medium dark:text-white">Small</div>
                    <Progress progress={45} size="sm" />
                    <div className="text-base font-medium dark:text-white">Default</div>
                    <Progress progress={45} size="md" />
                    <div className="text-lg font-medium dark:text-white">Large</div>
                    <Progress progress={45} size="lg" />
                    <div className="text-lg font-medium dark:text-white">Extra Large</div>
                    <Progress progress={45} size="xl" />
                </div>
            </div>

        </>
    )
}
function Colors() {

    return (

        <>
            <div>
                <h2 className='text-center text-red-600 font-medium'>Colors</h2>


                <div className="flex flex-col gap-4">
                    <div className="space-y-1">
                        <div className="text-base font-medium dark:text-white">Dark</div>
                        <Progress progress={45} color="dark" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-blue-700 dark:text-blue-500">Blue</div>
                        <Progress progress={45} color="blue" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-red-700 dark:text-red-500">Red</div>
                        <Progress progress={45} color="red" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-green-700 dark:text-green-500">Green</div>
                        <Progress progress={45} color="green" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-yellow-700 dark:text-yellow-500">Yellow</div>
                        <Progress progress={45} color="yellow" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-indigo-700 dark:text-indigo-500">Indigo</div>
                        <Progress progress={45} color="indigo" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-purple-700 dark:text-purple-500">Purple</div>
                        <Progress progress={45} color="purple" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-cyan-700 dark:text-cyan-500">Cyan</div>
                        <Progress progress={45} color="cyan" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-gray-700 dark:text-gray-500">Gray</div>
                        <Progress progress={45} color="gray" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-lime-700 dark:text-lime-500">Lime</div>
                        <Progress progress={45} color="lime" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-pink-700 dark:text-pink-500">Pink</div>
                        <Progress progress={45} color="pink" />
                    </div>
                    <div className="space-y-1">
                        <div className="text-base font-medium text-teal-700 dark:text-teal-500">Teal</div>
                        <Progress progress={45} color="teal" />
                    </div>
                </div>
            </div>

        </>
    )
}