import React from 'react'
import { Spinner } from "flowbite-react";
export const metadata = {
  title: "Loading",
  description: "Generated by create next app",
};

export default function Loading() {
    return (
        <div className="flex flex-wrap gap-2">
          <Spinner color="info" aria-label="Info spinner example" />
          <Spinner color="success" aria-label="Success spinner example" />
          <Spinner color="failure" aria-label="Failure spinner example" />
          <Spinner color="warning" aria-label="Warning spinner example" />
          <Spinner color="pink" aria-label="Pink spinner example" />
          <Spinner color="purple" aria-label="Purple spinner example" />
        </div>
      );
}
