import React from 'react'
import Sidebar from '../Components/Sidebar'

export const metadata = {
    title: "Sidebar",
    description: "Generated by create next app",
  };

export default function page() {
    return (
        <div><Sidebar /></div>
    )
}
