import React from 'react'
import { Rating, RatingAdvanced, RatingStar } from "flowbite-react";

export const metadata = {
    title: "rating",
    description: "Generated by create next app",
};
export default function App_Rating() {
    return (
        <>
            <h1 className='text-center font-bold text-blue-600 text-[25px] underline decoration-dotted'>Rating</h1>
            <div className='grid grid-cols-4 justify-between'>

                <Default_rating />
                <Rating_with_text />
                <Rating_count />
                <Star_sizing />
                <Advanced_rating />


            </div>

        </>
    )
}

function Default_rating() {

    return (

        <>
            <div>
                <h2>Default_rating</h2>


                <Rating>
                    <RatingStar />
                    <RatingStar />
                    <RatingStar />
                    <RatingStar />
                    <RatingStar filled={false} />
                </Rating>
            </div>

        </>
    )
}
function Rating_with_text() {

    return (

        <>
            <div>
                <h2>Rating_with_text</h2>


                <Rating>
                    <RatingStar />
                    <RatingStar />
                    <RatingStar />
                    <RatingStar />
                    <RatingStar filled={false} />
                    <p className="ml-2 text-sm font-medium text-gray-500 dark:text-gray-400">4.95 out of 5</p>
                </Rating>
            </div>

        </>
    )
}
function Rating_count() {

    return (

        <>
            <div>
                <h2>Rating_count</h2>


                <Rating>
                    <RatingStar />
                    <RatingStar />
                    <RatingStar />
                    <RatingStar />
                    <RatingStar filled={false} />
                </Rating>
            </div>

        </>
    )
}
function Star_sizing() {

    return (

        <>
            <div>
                <h2>Star_sizing</h2>


                <div className="flex flex-col gap-2">
                    <Rating>
                        <RatingStar />
                        <RatingStar />
                        <RatingStar />
                        <RatingStar />
                        <RatingStar filled={false} />
                    </Rating>
                    <Rating size="md">
                        <RatingStar />
                        <RatingStar />
                        <RatingStar />
                        <RatingStar />
                        <RatingStar filled={false} />
                    </Rating>
                    <Rating size="lg">
                        <RatingStar />
                        <RatingStar />
                        <RatingStar />
                        <RatingStar />
                        <RatingStar filled={false} />
                    </Rating>
                </div>
            </div>

        </>
    )
}
function Advanced_rating() {

    return (

        <>
            <div>
                <h2>Advanced_rating</h2>


                <Rating className="mb-2">
                    <RatingStar />
                    <RatingStar />
                    <RatingStar />
                    <RatingStar />
                    <RatingStar filled={false} />
                    <p className="ml-2 text-sm font-medium text-gray-500 dark:text-gray-400">4.95 out of 5</p>
                </Rating>
                <p className="mb-4 text-sm font-medium text-gray-500 dark:text-gray-400">1,745 global ratings</p>
                <RatingAdvanced percentFilled={70} className="mb-2">
                    5 star
                </RatingAdvanced>
                <RatingAdvanced percentFilled={17} className="mb-2">
                    4 star
                </RatingAdvanced>
                <RatingAdvanced percentFilled={8} className="mb-2">
                    3 star
                </RatingAdvanced>
                <RatingAdvanced percentFilled={4} className="mb-2">
                    2 star
                </RatingAdvanced>
                <RatingAdvanced percentFilled={1}>1 star</RatingAdvanced>
            </div>

        </>
    )
}