import React from 'react'
import { Button, Spinner } from "flowbite-react";


export const metadata = {
    title: "TabReact Spinner (Loader) - Flowbites",
    description: "Generated by create next app",
};
export default function App_Spinner() {
    return (
        <>
            <h1 className="text-center text-blue-600 font-bold text-xl mb-6">
                React Spinner (Loader) - Flowbite
            </h1>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 max-w-[1170px] mx-auto px-4">
                <Default_spinner />
                <Spinner_colors />
                <Sizing_options />
                <Alignment />
                <Loading_buttons />
            </div>

        </>
    )
}

function Default_spinner() {

    return (

        <>
            <div>
                <h2 className='text-center text-red-600 font-medium'>Default_spinner</h2>


                <Spinner aria-label="Default status example" />            </div>

        </>
    )
}
function Spinner_colors() {

    return (

        <>
            <div>
                <h2 className='text-center text-red-600 font-medium'>Spinner_colors</h2>


                <div className="flex flex-wrap gap-2">
                    <Spinner color="info" aria-label="Info spinner example" />
                    <Spinner color="success" aria-label="Success spinner example" />
                    <Spinner color="failure" aria-label="Failure spinner example" />
                    <Spinner color="warning" aria-label="Warning spinner example" />
                    <Spinner color="pink" aria-label="Pink spinner example" />
                    <Spinner color="purple" aria-label="Purple spinner example" />
                </div>            </div>

        </>
    )
}
function Sizing_options() {

    return (

        <>
            <div>
                <h2 className='text-center text-red-600 font-medium'>Sizing_options</h2>


                <div className="flex flex-wrap items-center gap-2">
                    <Spinner aria-label="Extra small spinner example" size="xs" />
                    <Spinner aria-label="Small spinner example" size="sm" />
                    <Spinner aria-label="Medium sized spinner example" size="md" />
                    <Spinner aria-label="Large spinner example" size="lg" />
                    <Spinner aria-label="Extra large spinner example" size="xl" />
                </div>            </div>

        </>
    )
}
function Alignment() {

    return (

        <>
            <div>
                <h2 className='text-center text-red-600 font-medium'>Default_spinner</h2>


                <div className="flex flex-col gap-2">
                    <div className="text-left">
                        <Spinner aria-label="Left-aligned spinner example" />
                    </div>
                    <div className="text-center">
                        <Spinner aria-label="Center-aligned spinner example" />
                    </div>
                    <div className="text-right">
                        <Spinner aria-label="Right-aligned spinner example" />
                    </div>
                </div>            </div>

        </>
    )
}
function Loading_buttons() {

    return (

        <>
            <div>
                <h2 className='text-center text-red-600 font-medium'>Loading_buttons</h2>


                <div className="flex flex-row gap-3">
                    <Button>
                        <Spinner aria-label="Spinner button example" size="sm" light />
                        <span className="pl-3">Loading...</span>
                    </Button>
                    <Button color="alternative">
                        <Spinner aria-label="Alternate spinner button example" size="sm" />
                        <span className="pl-3">Loading...</span>
                    </Button>
                </div>            </div>

        </>
    )
}