import React from 'react'
import { Button, ButtonGroup } from "flowbite-react";
import { HiAdjustments, HiCloudDownload, HiUserCircle } from "react-icons/hi";


export const metadata = {
    title: "Button_Group_Flowbite",
    description: "Generated by create next app",
  };
export default function Button_Group_Flowbite() {
    return (
        <>
            <h1 className='text-center font-bold text-blue-600 text-[25px] underline decoration-dotted'>React Button Group - Flowbite</h1>
            <div>
                <Defaultbuttongroup />
                <Button_group_with_icons />
                <Outline_button_group />
                <Outline_button_group_with_icons/>
                <Color_options/>



            </div>


        </>
    )
}
function Defaultbuttongroup() {

    return (

        <>
            <h2 className='text-center text-red-600 font-medium'>Default button group</h2>

            <ButtonGroup>
                <Button color="alternative">Profile</Button>
                <Button color="alternative">Settings</Button>
                <Button color="alternative">Messages</Button>
            </ButtonGroup>


        </>
    )
}
function Button_group_with_icons() {

    return (

        <>
            <h2 className='text-center text-red-600 font-medium'>Button group with icons</h2>

            <ButtonGroup>
                <Button color="alternative">
                    <HiUserCircle className="me-2 h-4 w-4" />
                    Profile
                </Button>
                <Button color="alternative">
                    <HiAdjustments className="me-2 h-4 w-4" />
                    Settings
                </Button>
                <Button color="alternative">
                    <HiCloudDownload className="me-2 h-4 w-4" />
                    Messages
                </Button>
            </ButtonGroup>


        </>
    )
}
function Outline_button_group() {

    return (

        <>
            <h2 className='text-center text-red-600 font-medium'>Outline_button_group</h2>

            <ButtonGroup outline>
                <Button>Profile</Button>
                <Button>Settings</Button>
                <Button>Messages</Button>
            </ButtonGroup>


        </>
    )
}
function Outline_button_group_with_icons() {

    return (

        <>
            <h2 className='text-center text-red-600 font-medium'>Outline_button_group_with_icons</h2>

            <ButtonGroup outline>
      <Button>
        <HiUserCircle className="me-2 h-4 w-4" />
        Profile
      </Button>
      <Button>
        <HiAdjustments className="me-2 h-4 w-4" />
        Settings
      </Button>
      <Button>
        <HiCloudDownload className="me-3 h-4 w-4" />
        Messages
      </Button>
    </ButtonGroup>


        </>
    )
}
function Color_options() {

    return (

        <>
            <h2 className='text-center text-red-600 font-medium'>Color_options</h2>

            <ButtonGroup>
      <Button color="cyan">Profile</Button>
      <Button color="cyan">Settings</Button>
      <Button color="cyan">Messages</Button>
    </ButtonGroup>


        </>
    )
}