import React from 'react'
import Modal_Flowbite from '../Components/Modal - Flowbite'
export const metadata = {
    title: "Modal",
    description: "Generated by create next app",
  };
export default function page() {
  return (
    <div>

        <Modal_Flowbite/>
    </div>
  )
}
