import React from 'react'
import Dropdown_flowbite from '../Components/Dropdown_flowbite'

export const metadata = {
    title: "Dropdown flowbite",
    description: "Generated by create next app",
  };

export default function page() {
  return (
    <div><Dropdown_flowbite/></div>
  )
}
